[FD-1384] Add Search API Support to Table Variables
NIH-NCPI/locutus pull request #21
Opened 2024-08-12 19:03 UTC by brendagutman

2024-08-26 22:03 UTC, torstees requested changes
I think most of the work is fine, but there is a design issue I have with storing the preferences directly inside the coding. Also, there are some more minor issues mentioned in comments.

2024-08-26 22:03 UTC, torstees commented on src/locutus/model/terminology.py
> +    def __init__(self, code, display="", system=None, description="", api_preference=None):
I'm not really loving this. While this is a legitimate place to store these, I'm more inclined to see it as something that would live in it's own collection, similar to how we are storing mappings and provenance. The reason being that these codings are intended to represent something very basic, and these extensions are layers that are very specific to our application. If we stored information like this in the coding, we would need to filter it out before passing code systems and value sets to other systems (and the front end in certain places)

2024-08-26 22:03 UTC, torstees commented on src/locutus/model/terminology.py
> +        AddPreference = "Add API Ontology Preference"
I see now why you were adding that editor property. However, I don't think these are necessary.

2024-08-28 19:06 UTC, brendagutman commented on src/locutus/api/table.py
> +from locutus.model.terminology import Terminology
required for the `ChangeType` ln ~162

2024-08-29 16:11 UTC, torstees approved these changes
This looks great! I did suggest replacing your H4 tags with the markdown equivalent of "####" in your README, if you don't need to specify that id yourself just to be consistent.

2024-08-29 16:11 UTC, torstees commented on README.md
> +<h4 id="table_id_filter_code_get">GET</h4>
Those "#" characters are this flavor of Markdown's header indication. So, H4 is four pound signs: "#### GET" would be the same as your h4 tag above, unless you need that id to be specific.

2024-08-29 17:04 UTC, merged