[FD-1504] Add standard terminology to a Terminology Collection
NIH-NCPI/locutus pull request #38
Opened 2024-09-10 19:44 UTC by brendagutman

2024-09-10 19:57 UTC, brendagutman commented on README.md
> +### https://[APPURL]/api/Terminology/[id]/standard
Not sure what we want the endpoint to be.

Also,
I use `standard_terminology` to define the references throughout this PR.
Let me know if we wanted different language surrounding this entirely. Should `standard_terminology` be something else (`prefered_terminology`) ?

2024-09-11 23:37 UTC, torstees requested changes
This is very close but there are a few suggestions.

2024-09-11 23:37 UTC, torstees commented on src/locutus/model/terminology.py
> +            "reference": [
Let's change this to 
[
  { 
     "reference": "Terminology/tm--asdfasdf"
  },
  { 
    "reference": "Terminology/tm-fdsa-fdsa"
  }
]

If you want to return an object, then you could name the array you return. Also, those reference strings will not start with a slash. It's just {ResourceType}/{id} -- blatant stealing from FHIR.

2024-09-11 23:37 UTC, torstees commented on src/locutus/api/terminology.py
> +            "terminology": {"Reference being mapped": f"Terminology/{t.id}"},
I'm inclined to think this should be:
response = {
  "id": t.id,
  "preferred_terminology": preferred_terminology,
}
If you want to return the reference details for the terminology you are changing, you should make it a formal reference (so "Reference being mapped" would be "reference"). But, I think id is fine.

2024-09-11 23:37 UTC, torstees commented on src/locutus/model/terminology.py
> +            new_pref = {key: f"/Terminology/{preferred_terminology}"}
If these are actual reference strings, that "/" at the beginning doesn't need to be there.

2024-09-11 23:37 UTC, torstees commented on README.md
> +        "reference_1": "/Terminology/tm--example1",
Let's break this into two distinct references, one to tm--example1 and the other tm--example2, each as full blown references

"references": [
  { "reference": "Terminology/tm--example1"},
  {"reference": "Terminology/tm--example2"}
]

2024-09-16 21:51 UTC, torstees approved these changes
looks good to me.

2024-09-17 17:44 UTC, merged